void SDL_AddEventWatch() { __builtin_trap(); }
void SDL_AddHintCallback() { __builtin_trap(); }
void SDL_AddTimer() { __builtin_trap(); }
void SDL_AllocFormat() { __builtin_trap(); }
void SDL_AllocPalette() { __builtin_trap(); }
void SDL_AllocRW() { __builtin_trap(); }
void SDL_AtomicAdd() { __builtin_trap(); }
void SDL_AtomicCAS() { __builtin_trap(); }
void SDL_AtomicCASPtr() { __builtin_trap(); }
void SDL_AtomicGet() { __builtin_trap(); }
void SDL_AtomicGetPtr() { __builtin_trap(); }
void SDL_AtomicLock() { __builtin_trap(); }
void SDL_AtomicSet() { __builtin_trap(); }
void SDL_AtomicSetPtr() { __builtin_trap(); }
void SDL_AtomicTryLock() { __builtin_trap(); }
void SDL_AtomicUnlock() { __builtin_trap(); }
void SDL_AudioInit() { __builtin_trap(); }
void SDL_AudioQuit() { __builtin_trap(); }
void SDL_AudioStreamAvailable() { __builtin_trap(); }
void SDL_AudioStreamClear() { __builtin_trap(); }
void SDL_AudioStreamFlush() { __builtin_trap(); }
void SDL_AudioStreamGet() { __builtin_trap(); }
void SDL_AudioStreamPut() { __builtin_trap(); }
void SDL_BuildAudioCVT() { __builtin_trap(); }
void SDL_CalculateGammaRamp() { __builtin_trap(); }
void SDL_CaptureMouse() { __builtin_trap(); }
void SDL_ClearError() { __builtin_trap(); }
void SDL_ClearHints() { __builtin_trap(); }
void SDL_ClearQueuedAudio() { __builtin_trap(); }
void SDL_CloseAudio() { __builtin_trap(); }
void SDL_CloseAudioDevice() { __builtin_trap(); }
void SDL_ComposeCustomBlendMode() { __builtin_trap(); }
void SDL_CondBroadcast() { __builtin_trap(); }
void SDL_CondSignal() { __builtin_trap(); }
void SDL_CondWait() { __builtin_trap(); }
void SDL_CondWaitTimeout() { __builtin_trap(); }
void SDL_ConvertAudio() { __builtin_trap(); }
void SDL_ConvertPixels() { __builtin_trap(); }
void SDL_ConvertSurface() { __builtin_trap(); }
void SDL_ConvertSurfaceFormat() { __builtin_trap(); }
void SDL_CreateColorCursor() { __builtin_trap(); }
void SDL_CreateCond() { __builtin_trap(); }
void SDL_CreateCursor() { __builtin_trap(); }
void SDL_CreateMutex() { __builtin_trap(); }
void SDL_CreateRGBSurface() { __builtin_trap(); }
void SDL_CreateRGBSurfaceFrom() { __builtin_trap(); }
void SDL_CreateRGBSurfaceWithFormat() { __builtin_trap(); }
void SDL_CreateRGBSurfaceWithFormatFrom() { __builtin_trap(); }
void SDL_CreateRenderer() { __builtin_trap(); }
void SDL_CreateSemaphore() { __builtin_trap(); }
void SDL_CreateShapedWindow() { __builtin_trap(); }
void SDL_CreateSoftwareRenderer() { __builtin_trap(); }
void SDL_CreateSystemCursor() { __builtin_trap(); }
void SDL_CreateTexture() { __builtin_trap(); }
void SDL_CreateTextureFromSurface() { __builtin_trap(); }
void SDL_CreateThread() { __builtin_trap(); }
void SDL_CreateThreadWithStackSize() { __builtin_trap(); }
void SDL_CreateWindow() { __builtin_trap(); }
void SDL_CreateWindowAndRenderer() { __builtin_trap(); }
void SDL_CreateWindowFrom() { __builtin_trap(); }
void SDL_DYNAPI_entry() { __builtin_trap(); }
void SDL_DelEventWatch() { __builtin_trap(); }
void SDL_DelHintCallback() { __builtin_trap(); }
void SDL_Delay() { __builtin_trap(); }
void SDL_DequeueAudio() { __builtin_trap(); }
void SDL_DestroyCond() { __builtin_trap(); }
void SDL_DestroyMutex() { __builtin_trap(); }
void SDL_DestroyRenderer() { __builtin_trap(); }
void SDL_DestroySemaphore() { __builtin_trap(); }
void SDL_DestroyTexture() { __builtin_trap(); }
void SDL_DestroyWindow() { __builtin_trap(); }
void SDL_DetachThread() { __builtin_trap(); }
void SDL_DisableScreenSaver() { __builtin_trap(); }
void SDL_DuplicateSurface() { __builtin_trap(); }
void SDL_EnableScreenSaver() { __builtin_trap(); }
void SDL_EnclosePoints() { __builtin_trap(); }
void SDL_Error() { __builtin_trap(); }
void SDL_EventState() { __builtin_trap(); }
void SDL_FillRect() { __builtin_trap(); }
void SDL_FillRects() { __builtin_trap(); }
void SDL_FilterEvents() { __builtin_trap(); }
void SDL_FlushEvent() { __builtin_trap(); }
void SDL_FlushEvents() { __builtin_trap(); }
void SDL_FreeAudioStream() { __builtin_trap(); }
void SDL_FreeCursor() { __builtin_trap(); }
void SDL_FreeFormat() { __builtin_trap(); }
void SDL_FreePalette() { __builtin_trap(); }
void SDL_FreeRW() { __builtin_trap(); }
void SDL_FreeSurface() { __builtin_trap(); }
void SDL_FreeWAV() { __builtin_trap(); }
void SDL_GL_BindTexture() { __builtin_trap(); }
void SDL_GL_CreateContext() { __builtin_trap(); }
void SDL_GL_DeleteContext() { __builtin_trap(); }
void SDL_GL_ExtensionSupported() { __builtin_trap(); }
void SDL_GL_GetAttribute() { __builtin_trap(); }
void SDL_GL_GetCurrentContext() { __builtin_trap(); }
void SDL_GL_GetCurrentWindow() { __builtin_trap(); }
void SDL_GL_GetDrawableSize() { __builtin_trap(); }
void SDL_GL_GetProcAddress() { __builtin_trap(); }
void SDL_GL_GetSwapInterval() { __builtin_trap(); }
void SDL_GL_LoadLibrary() { __builtin_trap(); }
void SDL_GL_MakeCurrent() { __builtin_trap(); }
void SDL_GL_ResetAttributes() { __builtin_trap(); }
void SDL_GL_SetAttribute() { __builtin_trap(); }
void SDL_GL_SetSwapInterval() { __builtin_trap(); }
void SDL_GL_SwapWindow() { __builtin_trap(); }
void SDL_GL_UnbindTexture() { __builtin_trap(); }
void SDL_GL_UnloadLibrary() { __builtin_trap(); }
void SDL_GameControllerAddMapping() { __builtin_trap(); }
void SDL_GameControllerAddMappingsFromRW() { __builtin_trap(); }
void SDL_GameControllerClose() { __builtin_trap(); }
void SDL_GameControllerEventState() { __builtin_trap(); }
void SDL_GameControllerFromInstanceID() { __builtin_trap(); }
void SDL_GameControllerGetAttached() { __builtin_trap(); }
void SDL_GameControllerGetAxis() { __builtin_trap(); }
void SDL_GameControllerGetAxisFromString() { __builtin_trap(); }
void SDL_GameControllerGetBindForAxis() { __builtin_trap(); }
void SDL_GameControllerGetBindForButton() { __builtin_trap(); }
void SDL_GameControllerGetButton() { __builtin_trap(); }
void SDL_GameControllerGetButtonFromString() { __builtin_trap(); }
void SDL_GameControllerGetJoystick() { __builtin_trap(); }
void SDL_GameControllerGetPlayerIndex() { __builtin_trap(); }
void SDL_GameControllerGetProduct() { __builtin_trap(); }
void SDL_GameControllerGetProductVersion() { __builtin_trap(); }
void SDL_GameControllerGetStringForAxis() { __builtin_trap(); }
void SDL_GameControllerGetStringForButton() { __builtin_trap(); }
void SDL_GameControllerGetVendor() { __builtin_trap(); }
void SDL_GameControllerMapping() { __builtin_trap(); }
void SDL_GameControllerMappingForDeviceIndex() { __builtin_trap(); }
void SDL_GameControllerMappingForGUID() { __builtin_trap(); }
void SDL_GameControllerMappingForIndex() { __builtin_trap(); }
void SDL_GameControllerName() { __builtin_trap(); }
void SDL_GameControllerNameForIndex() { __builtin_trap(); }
void SDL_GameControllerNumMappings() { __builtin_trap(); }
void SDL_GameControllerOpen() { __builtin_trap(); }
void SDL_GameControllerRumble() { __builtin_trap(); }
void SDL_GameControllerUpdate() { __builtin_trap(); }
void SDL_GetAssertionHandler() { __builtin_trap(); }
void SDL_GetAssertionReport() { __builtin_trap(); }
void SDL_GetAudioDeviceName() { __builtin_trap(); }
void SDL_GetAudioDeviceStatus() { __builtin_trap(); }
void SDL_GetAudioDriver() { __builtin_trap(); }
void SDL_GetAudioStatus() { __builtin_trap(); }
void SDL_GetBasePath() { __builtin_trap(); }
void SDL_GetCPUCacheLineSize() { __builtin_trap(); }
void SDL_GetCPUCount() { __builtin_trap(); }
void SDL_GetClipRect() { __builtin_trap(); }
void SDL_GetClipboardText() { __builtin_trap(); }
void SDL_GetClosestDisplayMode() { __builtin_trap(); }
void SDL_GetColorKey() { __builtin_trap(); }
void SDL_GetCurrentAudioDriver() { __builtin_trap(); }
void SDL_GetCurrentDisplayMode() { __builtin_trap(); }
void SDL_GetCurrentVideoDriver() { __builtin_trap(); }
void SDL_GetCursor() { __builtin_trap(); }
void SDL_GetDefaultAssertionHandler() { __builtin_trap(); }
void SDL_GetDefaultCursor() { __builtin_trap(); }
void SDL_GetDesktopDisplayMode() { __builtin_trap(); }
void SDL_GetDisplayBounds() { __builtin_trap(); }
void SDL_GetDisplayDPI() { __builtin_trap(); }
void SDL_GetDisplayMode() { __builtin_trap(); }
void SDL_GetDisplayName() { __builtin_trap(); }
void SDL_GetDisplayOrientation() { __builtin_trap(); }
void SDL_GetDisplayUsableBounds() { __builtin_trap(); }
void SDL_GetError() { __builtin_trap(); }
void SDL_GetEventFilter() { __builtin_trap(); }
void SDL_GetGlobalMouseState() { __builtin_trap(); }
void SDL_GetGrabbedWindow() { __builtin_trap(); }
void SDL_GetHint() { __builtin_trap(); }
void SDL_GetHintBoolean() { __builtin_trap(); }
void SDL_GetKeyFromName() { __builtin_trap(); }
void SDL_GetKeyFromScancode() { __builtin_trap(); }
void SDL_GetKeyName() { __builtin_trap(); }
void SDL_GetKeyboardFocus() { __builtin_trap(); }
void SDL_GetKeyboardState() { __builtin_trap(); }
void SDL_GetMemoryFunctions() { __builtin_trap(); }
void SDL_GetModState() { __builtin_trap(); }
void SDL_GetMouseFocus() { __builtin_trap(); }
void SDL_GetMouseState() { __builtin_trap(); }
void SDL_GetNumAllocations() { __builtin_trap(); }
void SDL_GetNumAudioDevices() { __builtin_trap(); }
void SDL_GetNumAudioDrivers() { __builtin_trap(); }
void SDL_GetNumDisplayModes() { __builtin_trap(); }
void SDL_GetNumRenderDrivers() { __builtin_trap(); }
void SDL_GetNumTouchDevices() { __builtin_trap(); }
void SDL_GetNumTouchFingers() { __builtin_trap(); }
void SDL_GetNumVideoDisplays() { __builtin_trap(); }
void SDL_GetNumVideoDrivers() { __builtin_trap(); }
void SDL_GetPerformanceCounter() { __builtin_trap(); }
void SDL_GetPerformanceFrequency() { __builtin_trap(); }
void SDL_GetPixelFormatName() { __builtin_trap(); }
void SDL_GetPlatform() { __builtin_trap(); }
void SDL_GetPowerInfo() { __builtin_trap(); }
void SDL_GetPrefPath() { __builtin_trap(); }
void SDL_GetQueuedAudioSize() { __builtin_trap(); }
void SDL_GetRGB() { __builtin_trap(); }
void SDL_GetRGBA() { __builtin_trap(); }
void SDL_GetRelativeMouseMode() { __builtin_trap(); }
void SDL_GetRelativeMouseState() { __builtin_trap(); }
void SDL_GetRenderDrawBlendMode() { __builtin_trap(); }
void SDL_GetRenderDrawColor() { __builtin_trap(); }
void SDL_GetRenderDriverInfo() { __builtin_trap(); }
void SDL_GetRenderTarget() { __builtin_trap(); }
void SDL_GetRenderer() { __builtin_trap(); }
void SDL_GetRendererInfo() { __builtin_trap(); }
void SDL_GetRendererOutputSize() { __builtin_trap(); }
void SDL_GetRevision() { __builtin_trap(); }
void SDL_GetRevisionNumber() { __builtin_trap(); }
void SDL_GetScancodeFromKey() { __builtin_trap(); }
void SDL_GetScancodeFromName() { __builtin_trap(); }
void SDL_GetScancodeName() { __builtin_trap(); }
void SDL_GetShapedWindowMode() { __builtin_trap(); }
void SDL_GetSurfaceAlphaMod() { __builtin_trap(); }
void SDL_GetSurfaceBlendMode() { __builtin_trap(); }
void SDL_GetSurfaceColorMod() { __builtin_trap(); }
void SDL_GetSystemRAM() { __builtin_trap(); }
void SDL_GetTextureAlphaMod() { __builtin_trap(); }
void SDL_GetTextureBlendMode() { __builtin_trap(); }
void SDL_GetTextureColorMod() { __builtin_trap(); }
void SDL_GetThreadID() { __builtin_trap(); }
void SDL_GetThreadName() { __builtin_trap(); }
void SDL_GetTicks() { __builtin_trap(); }
void SDL_GetTouchDevice() { __builtin_trap(); }
void SDL_GetTouchDeviceType() { __builtin_trap(); }
void SDL_GetTouchFinger() { __builtin_trap(); }
void SDL_GetVersion() { __builtin_trap(); }
void SDL_GetVideoDriver() { __builtin_trap(); }
void SDL_GetWindowBordersSize() { __builtin_trap(); }
void SDL_GetWindowBrightness() { __builtin_trap(); }
void SDL_GetWindowData() { __builtin_trap(); }
void SDL_GetWindowDisplayIndex() { __builtin_trap(); }
void SDL_GetWindowDisplayMode() { __builtin_trap(); }
void SDL_GetWindowFlags() { __builtin_trap(); }
void SDL_GetWindowFromID() { __builtin_trap(); }
void SDL_GetWindowGammaRamp() { __builtin_trap(); }
void SDL_GetWindowGrab() { __builtin_trap(); }
void SDL_GetWindowID() { __builtin_trap(); }
void SDL_GetWindowMaximumSize() { __builtin_trap(); }
void SDL_GetWindowMinimumSize() { __builtin_trap(); }
void SDL_GetWindowOpacity() { __builtin_trap(); }
void SDL_GetWindowPixelFormat() { __builtin_trap(); }
void SDL_GetWindowPosition() { __builtin_trap(); }
void SDL_GetWindowSize() { __builtin_trap(); }
void SDL_GetWindowSurface() { __builtin_trap(); }
void SDL_GetWindowTitle() { __builtin_trap(); }
void SDL_GetWindowWMInfo() { __builtin_trap(); }
void SDL_GetYUVConversionMode() { __builtin_trap(); }
void SDL_GetYUVConversionModeForResolution() { __builtin_trap(); }
void SDL_HapticClose() { __builtin_trap(); }
void SDL_HapticDestroyEffect() { __builtin_trap(); }
void SDL_HapticEffectSupported() { __builtin_trap(); }
void SDL_HapticGetEffectStatus() { __builtin_trap(); }
void SDL_HapticIndex() { __builtin_trap(); }
void SDL_HapticName() { __builtin_trap(); }
void SDL_HapticNewEffect() { __builtin_trap(); }
void SDL_HapticNumAxes() { __builtin_trap(); }
void SDL_HapticNumEffects() { __builtin_trap(); }
void SDL_HapticNumEffectsPlaying() { __builtin_trap(); }
void SDL_HapticOpen() { __builtin_trap(); }
void SDL_HapticOpenFromJoystick() { __builtin_trap(); }
void SDL_HapticOpenFromMouse() { __builtin_trap(); }
void SDL_HapticOpened() { __builtin_trap(); }
void SDL_HapticPause() { __builtin_trap(); }
void SDL_HapticQuery() { __builtin_trap(); }
void SDL_HapticRumbleInit() { __builtin_trap(); }
void SDL_HapticRumblePlay() { __builtin_trap(); }
void SDL_HapticRumbleStop() { __builtin_trap(); }
void SDL_HapticRumbleSupported() { __builtin_trap(); }
void SDL_HapticRunEffect() { __builtin_trap(); }
void SDL_HapticSetAutocenter() { __builtin_trap(); }
void SDL_HapticSetGain() { __builtin_trap(); }
void SDL_HapticStopAll() { __builtin_trap(); }
void SDL_HapticStopEffect() { __builtin_trap(); }
void SDL_HapticUnpause() { __builtin_trap(); }
void SDL_HapticUpdateEffect() { __builtin_trap(); }
void SDL_Has3DNow() { __builtin_trap(); }
void SDL_HasAVX() { __builtin_trap(); }
void SDL_HasAVX2() { __builtin_trap(); }
void SDL_HasAVX512F() { __builtin_trap(); }
void SDL_HasAltiVec() { __builtin_trap(); }
void SDL_HasClipboardText() { __builtin_trap(); }
void SDL_HasColorKey() { __builtin_trap(); }
void SDL_HasEvent() { __builtin_trap(); }
void SDL_HasEvents() { __builtin_trap(); }
void SDL_HasIntersection() { __builtin_trap(); }
void SDL_HasMMX() { __builtin_trap(); }
void SDL_HasNEON() { __builtin_trap(); }
void SDL_HasRDTSC() { __builtin_trap(); }
void SDL_HasSSE() { __builtin_trap(); }
void SDL_HasSSE2() { __builtin_trap(); }
void SDL_HasSSE3() { __builtin_trap(); }
void SDL_HasSSE41() { __builtin_trap(); }
void SDL_HasSSE42() { __builtin_trap(); }
void SDL_HasScreenKeyboardSupport() { __builtin_trap(); }
void SDL_HideWindow() { __builtin_trap(); }
void SDL_Init() { __builtin_trap(); }
void SDL_InitSubSystem() { __builtin_trap(); }
void SDL_IntersectRect() { __builtin_trap(); }
void SDL_IntersectRectAndLine() { __builtin_trap(); }
void SDL_IsGameController() { __builtin_trap(); }
void SDL_IsScreenKeyboardShown() { __builtin_trap(); }
void SDL_IsScreenSaverEnabled() { __builtin_trap(); }
void SDL_IsShapedWindow() { __builtin_trap(); }
void SDL_IsTablet() { __builtin_trap(); }
void SDL_IsTextInputActive() { __builtin_trap(); }
void SDL_JoystickClose() { __builtin_trap(); }
void SDL_JoystickCurrentPowerLevel() { __builtin_trap(); }
void SDL_JoystickEventState() { __builtin_trap(); }
void SDL_JoystickFromInstanceID() { __builtin_trap(); }
void SDL_JoystickGetAttached() { __builtin_trap(); }
void SDL_JoystickGetAxis() { __builtin_trap(); }
void SDL_JoystickGetAxisInitialState() { __builtin_trap(); }
void SDL_JoystickGetBall() { __builtin_trap(); }
void SDL_JoystickGetButton() { __builtin_trap(); }
void SDL_JoystickGetDeviceGUID() { __builtin_trap(); }
void SDL_JoystickGetDeviceInstanceID() { __builtin_trap(); }
void SDL_JoystickGetDevicePlayerIndex() { __builtin_trap(); }
void SDL_JoystickGetDeviceProduct() { __builtin_trap(); }
void SDL_JoystickGetDeviceProductVersion() { __builtin_trap(); }
void SDL_JoystickGetDeviceType() { __builtin_trap(); }
void SDL_JoystickGetDeviceVendor() { __builtin_trap(); }
void SDL_JoystickGetGUID() { __builtin_trap(); }
void SDL_JoystickGetGUIDFromString() { __builtin_trap(); }
void SDL_JoystickGetGUIDString() { __builtin_trap(); }
void SDL_JoystickGetHat() { __builtin_trap(); }
void SDL_JoystickGetPlayerIndex() { __builtin_trap(); }
void SDL_JoystickGetProduct() { __builtin_trap(); }
void SDL_JoystickGetProductVersion() { __builtin_trap(); }
void SDL_JoystickGetType() { __builtin_trap(); }
void SDL_JoystickGetVendor() { __builtin_trap(); }
void SDL_JoystickInstanceID() { __builtin_trap(); }
void SDL_JoystickIsHaptic() { __builtin_trap(); }
void SDL_JoystickName() { __builtin_trap(); }
void SDL_JoystickNameForIndex() { __builtin_trap(); }
void SDL_JoystickNumAxes() { __builtin_trap(); }
void SDL_JoystickNumBalls() { __builtin_trap(); }
void SDL_JoystickNumButtons() { __builtin_trap(); }
void SDL_JoystickNumHats() { __builtin_trap(); }
void SDL_JoystickOpen() { __builtin_trap(); }
void SDL_JoystickRumble() { __builtin_trap(); }
void SDL_JoystickUpdate() { __builtin_trap(); }
void SDL_LinuxSetThreadPriority() { __builtin_trap(); }
void SDL_LoadBMP_RW() { __builtin_trap(); }
void SDL_LoadDollarTemplates() { __builtin_trap(); }
void SDL_LoadFile() { __builtin_trap(); }
void SDL_LoadFile_RW() { __builtin_trap(); }
void SDL_LoadFunction() { __builtin_trap(); }
void SDL_LoadObject() { __builtin_trap(); }
void SDL_LoadWAV_RW() { __builtin_trap(); }
void SDL_LockAudio() { __builtin_trap(); }
void SDL_LockAudioDevice() { __builtin_trap(); }
void SDL_LockJoysticks() { __builtin_trap(); }
void SDL_LockMutex() { __builtin_trap(); }
void SDL_LockSurface() { __builtin_trap(); }
void SDL_LockTexture() { __builtin_trap(); }
void SDL_Log() { __builtin_trap(); }
void SDL_LogCritical() { __builtin_trap(); }
void SDL_LogDebug() { __builtin_trap(); }
void SDL_LogError() { __builtin_trap(); }
void SDL_LogGetOutputFunction() { __builtin_trap(); }
void SDL_LogGetPriority() { __builtin_trap(); }
void SDL_LogInfo() { __builtin_trap(); }
void SDL_LogMessage() { __builtin_trap(); }
void SDL_LogMessageV() { __builtin_trap(); }
void SDL_LogResetPriorities() { __builtin_trap(); }
void SDL_LogSetAllPriority() { __builtin_trap(); }
void SDL_LogSetOutputFunction() { __builtin_trap(); }
void SDL_LogSetPriority() { __builtin_trap(); }
void SDL_LogVerbose() { __builtin_trap(); }
void SDL_LogWarn() { __builtin_trap(); }
void SDL_LowerBlit() { __builtin_trap(); }
void SDL_LowerBlitScaled() { __builtin_trap(); }
void SDL_MapRGB() { __builtin_trap(); }
void SDL_MapRGBA() { __builtin_trap(); }
void SDL_MasksToPixelFormatEnum() { __builtin_trap(); }
void SDL_MaximizeWindow() { __builtin_trap(); }
void SDL_MemoryBarrierAcquireFunction() { __builtin_trap(); }
void SDL_MemoryBarrierReleaseFunction() { __builtin_trap(); }
void SDL_MinimizeWindow() { __builtin_trap(); }
void SDL_MixAudio() { __builtin_trap(); }
void SDL_MixAudioFormat() { __builtin_trap(); }
void SDL_MouseIsHaptic() { __builtin_trap(); }
void SDL_NewAudioStream() { __builtin_trap(); }
void SDL_NumHaptics() { __builtin_trap(); }
void SDL_NumJoysticks() { __builtin_trap(); }
void SDL_NumSensors() { __builtin_trap(); }
void SDL_OpenAudio() { __builtin_trap(); }
void SDL_OpenAudioDevice() { __builtin_trap(); }
void SDL_PauseAudio() { __builtin_trap(); }
void SDL_PauseAudioDevice() { __builtin_trap(); }
void SDL_PeepEvents() { __builtin_trap(); }
void SDL_PixelFormatEnumToMasks() { __builtin_trap(); }
void SDL_PollEvent() { __builtin_trap(); }
void SDL_PumpEvents() { __builtin_trap(); }
void SDL_PushEvent() { __builtin_trap(); }
void SDL_QueryTexture() { __builtin_trap(); }
void SDL_QueueAudio() { __builtin_trap(); }
void SDL_Quit() { __builtin_trap(); }
void SDL_QuitSubSystem() { __builtin_trap(); }
void SDL_RWFromConstMem() { __builtin_trap(); }
void SDL_RWFromFP() { __builtin_trap(); }
void SDL_RWFromFile() { __builtin_trap(); }
void SDL_RWFromMem() { __builtin_trap(); }
void SDL_RWclose() { __builtin_trap(); }
void SDL_RWread() { __builtin_trap(); }
void SDL_RWseek() { __builtin_trap(); }
void SDL_RWsize() { __builtin_trap(); }
void SDL_RWtell() { __builtin_trap(); }
void SDL_RWwrite() { __builtin_trap(); }
void SDL_RaiseWindow() { __builtin_trap(); }
void SDL_ReadBE16() { __builtin_trap(); }
void SDL_ReadBE32() { __builtin_trap(); }
void SDL_ReadBE64() { __builtin_trap(); }
void SDL_ReadLE16() { __builtin_trap(); }
void SDL_ReadLE32() { __builtin_trap(); }
void SDL_ReadLE64() { __builtin_trap(); }
void SDL_ReadU8() { __builtin_trap(); }
void SDL_RecordGesture() { __builtin_trap(); }
void SDL_RegisterEvents() { __builtin_trap(); }
void SDL_RemoveTimer() { __builtin_trap(); }
void SDL_RenderClear() { __builtin_trap(); }
void SDL_RenderCopy() { __builtin_trap(); }
void SDL_RenderCopyEx() { __builtin_trap(); }
void SDL_RenderCopyExF() { __builtin_trap(); }
void SDL_RenderCopyF() { __builtin_trap(); }
void SDL_RenderDrawLine() { __builtin_trap(); }
void SDL_RenderDrawLineF() { __builtin_trap(); }
void SDL_RenderDrawLines() { __builtin_trap(); }
void SDL_RenderDrawLinesF() { __builtin_trap(); }
void SDL_RenderDrawPoint() { __builtin_trap(); }
void SDL_RenderDrawPointF() { __builtin_trap(); }
void SDL_RenderDrawPoints() { __builtin_trap(); }
void SDL_RenderDrawPointsF() { __builtin_trap(); }
void SDL_RenderDrawRect() { __builtin_trap(); }
void SDL_RenderDrawRectF() { __builtin_trap(); }
void SDL_RenderDrawRects() { __builtin_trap(); }
void SDL_RenderDrawRectsF() { __builtin_trap(); }
void SDL_RenderFillRect() { __builtin_trap(); }
void SDL_RenderFillRectF() { __builtin_trap(); }
void SDL_RenderFillRects() { __builtin_trap(); }
void SDL_RenderFillRectsF() { __builtin_trap(); }
void SDL_RenderFlush() { __builtin_trap(); }
void SDL_RenderGetClipRect() { __builtin_trap(); }
void SDL_RenderGetIntegerScale() { __builtin_trap(); }
void SDL_RenderGetLogicalSize() { __builtin_trap(); }
void SDL_RenderGetMetalCommandEncoder() { __builtin_trap(); }
void SDL_RenderGetMetalLayer() { __builtin_trap(); }
void SDL_RenderGetScale() { __builtin_trap(); }
void SDL_RenderGetViewport() { __builtin_trap(); }
void SDL_RenderIsClipEnabled() { __builtin_trap(); }
void SDL_RenderPresent() { __builtin_trap(); }
void SDL_RenderReadPixels() { __builtin_trap(); }
void SDL_RenderSetClipRect() { __builtin_trap(); }
void SDL_RenderSetIntegerScale() { __builtin_trap(); }
void SDL_RenderSetLogicalSize() { __builtin_trap(); }
void SDL_RenderSetScale() { __builtin_trap(); }
void SDL_RenderSetViewport() { __builtin_trap(); }
void SDL_RenderTargetSupported() { __builtin_trap(); }
void SDL_ReportAssertion() { __builtin_trap(); }
void SDL_ResetAssertionReport() { __builtin_trap(); }
void SDL_RestoreWindow() { __builtin_trap(); }
void SDL_SIMDAlloc() { __builtin_trap(); }
void SDL_SIMDFree() { __builtin_trap(); }
void SDL_SIMDGetAlignment() { __builtin_trap(); }
void SDL_SaveAllDollarTemplates() { __builtin_trap(); }
void SDL_SaveBMP_RW() { __builtin_trap(); }
void SDL_SaveDollarTemplate() { __builtin_trap(); }
void SDL_SemPost() { __builtin_trap(); }
void SDL_SemTryWait() { __builtin_trap(); }
void SDL_SemValue() { __builtin_trap(); }
void SDL_SemWait() { __builtin_trap(); }
void SDL_SemWaitTimeout() { __builtin_trap(); }
void SDL_SensorClose() { __builtin_trap(); }
void SDL_SensorFromInstanceID() { __builtin_trap(); }
void SDL_SensorGetData() { __builtin_trap(); }
void SDL_SensorGetDeviceInstanceID() { __builtin_trap(); }
void SDL_SensorGetDeviceName() { __builtin_trap(); }
void SDL_SensorGetDeviceNonPortableType() { __builtin_trap(); }
void SDL_SensorGetDeviceType() { __builtin_trap(); }
void SDL_SensorGetInstanceID() { __builtin_trap(); }
void SDL_SensorGetName() { __builtin_trap(); }
void SDL_SensorGetNonPortableType() { __builtin_trap(); }
void SDL_SensorGetType() { __builtin_trap(); }
void SDL_SensorOpen() { __builtin_trap(); }
void SDL_SensorUpdate() { __builtin_trap(); }
void SDL_SetAssertionHandler() { __builtin_trap(); }
void SDL_SetClipRect() { __builtin_trap(); }
void SDL_SetClipboardText() { __builtin_trap(); }
void SDL_SetColorKey() { __builtin_trap(); }
void SDL_SetCursor() { __builtin_trap(); }
void SDL_SetError() { __builtin_trap(); }
void SDL_SetEventFilter() { __builtin_trap(); }
void SDL_SetHint() { __builtin_trap(); }
void SDL_SetHintWithPriority() { __builtin_trap(); }
void SDL_SetMainReady() { __builtin_trap(); }
void SDL_SetMemoryFunctions() { __builtin_trap(); }
void SDL_SetModState() { __builtin_trap(); }
void SDL_SetPaletteColors() { __builtin_trap(); }
void SDL_SetPixelFormatPalette() { __builtin_trap(); }
void SDL_SetRelativeMouseMode() { __builtin_trap(); }
void SDL_SetRenderDrawBlendMode() { __builtin_trap(); }
void SDL_SetRenderDrawColor() { __builtin_trap(); }
void SDL_SetRenderTarget() { __builtin_trap(); }
void SDL_SetSurfaceAlphaMod() { __builtin_trap(); }
void SDL_SetSurfaceBlendMode() { __builtin_trap(); }
void SDL_SetSurfaceColorMod() { __builtin_trap(); }
void SDL_SetSurfacePalette() { __builtin_trap(); }
void SDL_SetSurfaceRLE() { __builtin_trap(); }
void SDL_SetTextInputRect() { __builtin_trap(); }
void SDL_SetTextureAlphaMod() { __builtin_trap(); }
void SDL_SetTextureBlendMode() { __builtin_trap(); }
void SDL_SetTextureColorMod() { __builtin_trap(); }
void SDL_SetThreadPriority() { __builtin_trap(); }
void SDL_SetWindowBordered() { __builtin_trap(); }
void SDL_SetWindowBrightness() { __builtin_trap(); }
void SDL_SetWindowData() { __builtin_trap(); }
void SDL_SetWindowDisplayMode() { __builtin_trap(); }
void SDL_SetWindowFullscreen() { __builtin_trap(); }
void SDL_SetWindowGammaRamp() { __builtin_trap(); }
void SDL_SetWindowGrab() { __builtin_trap(); }
void SDL_SetWindowHitTest() { __builtin_trap(); }
void SDL_SetWindowIcon() { __builtin_trap(); }
void SDL_SetWindowInputFocus() { __builtin_trap(); }
void SDL_SetWindowMaximumSize() { __builtin_trap(); }
void SDL_SetWindowMinimumSize() { __builtin_trap(); }
void SDL_SetWindowModalFor() { __builtin_trap(); }
void SDL_SetWindowOpacity() { __builtin_trap(); }
void SDL_SetWindowPosition() { __builtin_trap(); }
void SDL_SetWindowResizable() { __builtin_trap(); }
void SDL_SetWindowShape() { __builtin_trap(); }
void SDL_SetWindowSize() { __builtin_trap(); }
void SDL_SetWindowTitle() { __builtin_trap(); }
void SDL_SetYUVConversionMode() { __builtin_trap(); }
void SDL_ShowCursor() { __builtin_trap(); }
void SDL_ShowMessageBox() { __builtin_trap(); }
void SDL_ShowSimpleMessageBox() { __builtin_trap(); }
void SDL_ShowWindow() { __builtin_trap(); }
void SDL_SoftStretch() { __builtin_trap(); }
void SDL_StartTextInput() { __builtin_trap(); }
void SDL_StopTextInput() { __builtin_trap(); }
void SDL_TLSCreate() { __builtin_trap(); }
void SDL_TLSGet() { __builtin_trap(); }
void SDL_TLSSet() { __builtin_trap(); }
void SDL_ThreadID() { __builtin_trap(); }
void SDL_TryLockMutex() { __builtin_trap(); }
void SDL_UnionRect() { __builtin_trap(); }
void SDL_UnloadObject() { __builtin_trap(); }
void SDL_UnlockAudio() { __builtin_trap(); }
void SDL_UnlockAudioDevice() { __builtin_trap(); }
void SDL_UnlockJoysticks() { __builtin_trap(); }
void SDL_UnlockMutex() { __builtin_trap(); }
void SDL_UnlockSurface() { __builtin_trap(); }
void SDL_UnlockTexture() { __builtin_trap(); }
void SDL_UpdateTexture() { __builtin_trap(); }
void SDL_UpdateWindowSurface() { __builtin_trap(); }
void SDL_UpdateWindowSurfaceRects() { __builtin_trap(); }
void SDL_UpdateYUVTexture() { __builtin_trap(); }
void SDL_UpperBlit() { __builtin_trap(); }
void SDL_UpperBlitScaled() { __builtin_trap(); }
void SDL_VideoInit() { __builtin_trap(); }
void SDL_VideoQuit() { __builtin_trap(); }
void SDL_Vulkan_CreateSurface() { __builtin_trap(); }
void SDL_Vulkan_GetDrawableSize() { __builtin_trap(); }
void SDL_Vulkan_GetInstanceExtensions() { __builtin_trap(); }
void SDL_Vulkan_GetVkGetInstanceProcAddr() { __builtin_trap(); }
void SDL_Vulkan_LoadLibrary() { __builtin_trap(); }
void SDL_Vulkan_UnloadLibrary() { __builtin_trap(); }
void SDL_WaitEvent() { __builtin_trap(); }
void SDL_WaitEventTimeout() { __builtin_trap(); }
void SDL_WaitThread() { __builtin_trap(); }
void SDL_WarpMouseGlobal() { __builtin_trap(); }
void SDL_WarpMouseInWindow() { __builtin_trap(); }
void SDL_WasInit() { __builtin_trap(); }
void SDL_WriteBE16() { __builtin_trap(); }
void SDL_WriteBE32() { __builtin_trap(); }
void SDL_WriteBE64() { __builtin_trap(); }
void SDL_WriteLE16() { __builtin_trap(); }
void SDL_WriteLE32() { __builtin_trap(); }
void SDL_WriteLE64() { __builtin_trap(); }
void SDL_WriteU8() { __builtin_trap(); }
void SDL_abs() { __builtin_trap(); }
void SDL_acos() { __builtin_trap(); }
void SDL_acosf() { __builtin_trap(); }
void SDL_asin() { __builtin_trap(); }
void SDL_asinf() { __builtin_trap(); }
void SDL_atan() { __builtin_trap(); }
void SDL_atan2() { __builtin_trap(); }
void SDL_atan2f() { __builtin_trap(); }
void SDL_atanf() { __builtin_trap(); }
void SDL_atof() { __builtin_trap(); }
void SDL_atoi() { __builtin_trap(); }
void SDL_calloc() { __builtin_trap(); }
void SDL_ceil() { __builtin_trap(); }
void SDL_ceilf() { __builtin_trap(); }
void SDL_copysign() { __builtin_trap(); }
void SDL_copysignf() { __builtin_trap(); }
void SDL_cos() { __builtin_trap(); }
void SDL_cosf() { __builtin_trap(); }
void SDL_exp() { __builtin_trap(); }
void SDL_expf() { __builtin_trap(); }
void SDL_fabs() { __builtin_trap(); }
void SDL_fabsf() { __builtin_trap(); }
void SDL_floor() { __builtin_trap(); }
void SDL_floorf() { __builtin_trap(); }
void SDL_fmod() { __builtin_trap(); }
void SDL_fmodf() { __builtin_trap(); }
void SDL_free() { __builtin_trap(); }
void SDL_getenv() { __builtin_trap(); }
void SDL_iconv() { __builtin_trap(); }
void SDL_iconv_close() { __builtin_trap(); }
void SDL_iconv_open() { __builtin_trap(); }
void SDL_iconv_string() { __builtin_trap(); }
void SDL_isdigit() { __builtin_trap(); }
void SDL_isspace() { __builtin_trap(); }
void SDL_itoa() { __builtin_trap(); }
void SDL_lltoa() { __builtin_trap(); }
void SDL_log() { __builtin_trap(); }
void SDL_log10() { __builtin_trap(); }
void SDL_log10f() { __builtin_trap(); }
void SDL_logf() { __builtin_trap(); }
void SDL_ltoa() { __builtin_trap(); }
void SDL_malloc() { __builtin_trap(); }
void SDL_memcmp() { __builtin_trap(); }
void SDL_memcpy() { __builtin_trap(); }
void SDL_memmove() { __builtin_trap(); }
void SDL_memset() { __builtin_trap(); }
void SDL_pow() { __builtin_trap(); }
void SDL_powf() { __builtin_trap(); }
void SDL_qsort() { __builtin_trap(); }
void SDL_realloc() { __builtin_trap(); }
void SDL_scalbn() { __builtin_trap(); }
void SDL_scalbnf() { __builtin_trap(); }
void SDL_setenv() { __builtin_trap(); }
void SDL_sin() { __builtin_trap(); }
void SDL_sinf() { __builtin_trap(); }
void SDL_snprintf() { __builtin_trap(); }
void SDL_sqrt() { __builtin_trap(); }
void SDL_sqrtf() { __builtin_trap(); }
void SDL_sscanf() { __builtin_trap(); }
void SDL_strcasecmp() { __builtin_trap(); }
void SDL_strchr() { __builtin_trap(); }
void SDL_strcmp() { __builtin_trap(); }
void SDL_strdup() { __builtin_trap(); }
void SDL_strlcat() { __builtin_trap(); }
void SDL_strlcpy() { __builtin_trap(); }
void SDL_strlen() { __builtin_trap(); }
void SDL_strlwr() { __builtin_trap(); }
void SDL_strncasecmp() { __builtin_trap(); }
void SDL_strncmp() { __builtin_trap(); }
void SDL_strrchr() { __builtin_trap(); }
void SDL_strrev() { __builtin_trap(); }
void SDL_strstr() { __builtin_trap(); }
void SDL_strtod() { __builtin_trap(); }
void SDL_strtol() { __builtin_trap(); }
void SDL_strtoll() { __builtin_trap(); }
void SDL_strtoul() { __builtin_trap(); }
void SDL_strtoull() { __builtin_trap(); }
void SDL_strupr() { __builtin_trap(); }
void SDL_tan() { __builtin_trap(); }
void SDL_tanf() { __builtin_trap(); }
void SDL_tolower() { __builtin_trap(); }
void SDL_toupper() { __builtin_trap(); }
void SDL_uitoa() { __builtin_trap(); }
void SDL_ulltoa() { __builtin_trap(); }
void SDL_ultoa() { __builtin_trap(); }
void SDL_utf8strlcpy() { __builtin_trap(); }
void SDL_utf8strlen() { __builtin_trap(); }
void SDL_vsnprintf() { __builtin_trap(); }
void SDL_vsscanf() { __builtin_trap(); }
void SDL_wcscmp() { __builtin_trap(); }
void SDL_wcsdup() { __builtin_trap(); }
void SDL_wcslcat() { __builtin_trap(); }
void SDL_wcslcpy() { __builtin_trap(); }
void SDL_wcslen() { __builtin_trap(); }
void __bss_start() { __builtin_trap(); }
void _edata() { __builtin_trap(); }
void _end() { __builtin_trap(); }
